### ISSUE TITLE
Plugin submission for `com.scalified.plugins.gradle.it`

### ISSUE THREAD

**Issue by xaviarias** [Scalified/gradle-it-plugin#14]
Hi,

We received your plugin submission for `com.scalified.plugins.gradle.it`.

Your plugin was flagged for manual review because of the following issue(s):

- The newly published version of your plugin is removing the leading `gradle.plugin` from its JAR coordinates. This is a change we want to promote but know that it might impact users that rely on legacy plugin application.
 
Please let us know if this change is intentional or not. Without news from your side, we will approve the new submission in 3 days.

Also, your email address `vbaidak@users.noreply.github.com` is not valid, please update it so we can communicate using our standard channel.

Thanks!

**Comment by vbaidak** [comment]
Hi, @xaviarias !
I'm not sure I changed anything related to the plugin coordinates. Could you please provide more information?

Also, I can't change this email address since it is auto linked from Github

**Comment by xaviarias** [comment]
Hi,

Last plugin publish request was approved.

About your email, please change your GitHub email or provide a valid email so we can update our Plugin Portal database.

Thanks

**Comment by vbaidak** [comment]
@xaviarias , please change it to `vld.x@hotmail.com`

Thanks!

**Comment by vbaidak** [comment]
Е

**Comment by xaviarias** [comment]
Done
